### ISSUE TITLE
problem about training

### ISSUE THREAD

**Issue by www04576** [hova88/Lidardet#3]
Hi @hova88  , thank you so much for sharing such a nice work.
When I follow your instruction to train a model, I got an error:
`Traceback (most recent call last):
  File "/home/avep/rongxuan/Lidardet/libs/ops/non_max_suppression/nms_cpu.py", line 10, in <module>
    from libs.ops.non_max_suppression.nms import (
ImportError: libcudart.so.10.2: cannot open shared object file: No such file or directory`
I'm a newbie. Does this mean that the model can only be trained with CUDA 10.2? My CUDA Version is 11.4. And I can't find `libcudart.so.10.2` in `/usr/local/cuda/lib64`.
I would be very grateful if you reply to me.

**Comment by hova88** [comment]
I don't suggest you look at this repo as an introduction for your study. There are many problems in it, and I don't maintain it anymore. 

Recommend you to see openpcdet or mmdetection3d and so on....

**Comment by www04576** [comment]
@hova88 thank you for your quick response! 
I'm looking to find a model that can run on Xavier, and hopefully it's accelerated by tensorrt. I found [this](https://github.com/wangguojun2018/PointPillars_Tensorrt) on github, but his program doesn't work for our car scene. Your program fits our needs perfectly and is well documented, so thank you very much for your work.
If you think this repo is not suitable for continued use, can you recommend some suitable repos for me? Thanks!

**Comment by hova88** [comment]
> @hova88 thank you for your quick response! I'm looking to find a model that can run on Xavier, and hopefully it's accelerated by tensorrt. I found [this](https://github.com/wangguojun2018/PointPillars_Tensorrt) on github, but his program doesn't work for our car scene. Your program fits our needs perfectly and is well documented, so thank you very much for your work. If you think this repo is not suitable for continued use, can you recommend some suitable repos for me? Thanks!

https://github.com/NVIDIA-AI-IOT/CUDA-PointPillars
https://github.com/hova88/PointPillars_MultiHead_40FPS

**Comment by www04576** [comment]
Sorry I didn't make it clear. I've seen these two repos before and they're both great jobs. But I hope the program to run in ros so that it can read real-time data from rosbag or lidar. Neither of these repos seem to run in ros...

**Comment by hova88** [comment]
> Sorry I didn't make it clear. I've seen these two repos before and they're both great jobs. But I hope the program to run in ros so that it can read real-time data from rosbag or lidar. Neither of these repos seem to run in ros...

It's just that the interface is not written so ready-made. But that doesn't mean they can't run in ROS.

**Comment by www04576** [comment]
I know too little about this aspect. Thank you for telling me! I'll explore as you say. Wishing you happy every day.

**Comment by hova88** [comment]
> I know too little about this aspect. Thank you for telling me! I'll explore as you say. Wishing you happy every day.

(๑•̀ω•́)ノ thanks. You too.
